spring:
  pulsar:
    producer:
      message-routing-mode: custompartition
  docker:
    compose:
      # when run from Intellij via "Run" button, path must be set from project root
      file: spring-pulsar-sample-apps/sample-failover-custom-router/compose.yaml
