= Introduction
This project provides a basic Spring-friendly API for developing https://pulsar.apache.org/[Apache Pulsar] applications.

On a very high level, Spring for Apache Pulsar provides a `PulsarTemplate` for publishing to a Pulsar topic and a `PulsarListener` annotation for consuming from a Pulsar topic.
In addition, it also provides various convenience APIs for Spring developers to ramp up their development journey into Apache Pulsar.

include::project-state.adoc[leveloffset=+1]

== Supported Versions

The supported versions for the underlying libraries required by the framework are as follows:
|===
| Library | Minimum Version | Version Used

| Apache Pulsar
| 3.0.0
| {pulsar-client-version}

| Spring Framework
| 6.0.9
| {spring-framework-version}

| Spring Boot
| 3.2.0
| {spring-boot-version}

| Java
| 17
| -

| Gradle
| 7.4
| -

|===

NOTE: The **Version Used** is the version of the library targeted by Spring Pulsar  {spring-pulsar-version} (the version of the framework this reference guide belongs to).

Details for other versions and compatibility can be found in the <<version-compatibility.adoc#appendix.version-compatibility,appendix>>.

== Building the Project
If you have cloned the project locally, follow these steps to build the project from the source code.

Spring for Apache Pulsar uses Gradle as its build tool. Run the following command to do a full build of the project:
[indent=0]
----
./gradlew clean build
----
You can build without running tests by using the following command:
[indent=0]
----
./gradlew clean build -x test
----
