
include::attributes-variables.adoc[]

= Introduction
This project provides a basic Spring-friendly API for developing https://pulsar.apache.org/[Apache Pulsar] applications.

On a very high level, Spring for Apache Pulsar provides a `PulsarTemplate` for publishing to a Pulsar topic and a `PulsarListener` annotation for consuming from a Pulsar topic.
In addition, it also provides various convenience APIs for Spring developers to ramp up their development journey into Apache Pulsar.

include::project-state.adoc[leveloffset=+1]

== System Requirements

Spring for Apache Pulsar `{spring-pulsar-version}` requires the following:

- https://www.java.com[Java 17] and is compatible up to and including Java 20
- {spring-framework-docs}[Spring Framework `{spring-framework-version}`] or above
- {apache-pulsar-cient-docs}/[Apache Pulsar Java Client `{pulsar-client-version}`] or above

====
The version compatibility matrix (including Spring Boot) can be found in the <<version-compatibility.adoc#appendix.version-compatibility,appendix>>.
====

== Building the Project
If you have cloned the project locally, follow these steps to build the project from the source code.

NOTE: Gradle `7.x (7.4 or above)` is required to build.

Run the following command to do a full build of the project:
[indent=0]
----
./gradlew clean build
----
You can build without running tests by using the following command:
[indent=0]
----
./gradlew clean build -x test
----
