= Project Status
While the code and functionality of the framework is thoroughly tested and ready for production, the project is in a bit of flux while transitioning from experimental GA (`0.2.x`) to GA (`1.0.0`).

The evolution of the project (by version) is as follows:

[discrete]
== Version 0.2.x
All components (`the core + Spring Boot autoconfiguration + Spring Cloud Stream binder`) reside in the `spring-pulsar` Github repository.

This is considered an "experimental" GA, defined as:

- code and functionality is production ready, but decision has not been made to support the project permanently
- available on Maven Central using a major version of `0` to indicate its nature

[discrete]
== Version 1.0.x
This is the "full" GA and the components are split as follows (in-progress):

- the core stays in the `spring-pulsar` repo (`main` branch)
- the autoconfiguration moves to the Spring Boot project (targeting Spring Boot `3.2.0`)
- the binder moves to the Spring Cloud Stream project (targeting SCSt `4.1.0`)

NOTE: Until the GA release, the recommended version of the framework is `0.2.x`.
