spring:
  pulsar:
    defaults:
      type-mappings:
        - message-type: com.example.ImperativeProduceAndConsumeApp$Bar
          topic-name: bar-topic
          schema-info:
            schema-type: JSON
  docker:
    compose:
      file: spring-pulsar-sample-apps/sample-imperative-produce-consume/compose.yaml
