== Docker scripts for Pulsar

=== Pulsar Standalone
Runs a local standalone Pulsar cluster in Docker.

* The broker is available at  `pulsar://localhost:6650`.
* The admin is available at  `http://localhost:8080`
* Two Docker volumes (`pulsardata`, `pulsarconf`) are created to store the data, metadata, and configuration in order to not start "fresh" every time the container is restarted.

[#_start_pulsar]
==== Start
To start the cluster run the following script from project root dir:
[source,shell]
----
./tools/pulsar/docker/standalone/pulsar-start.sh
----

==== Stop
To stop the cluster run the following script from project root dir:
[source,shell]
----
./tools/pulsar/docker/standalone/pulsar-stop.sh
----

==== Destroy
To completely remove the cluster and volumes run the following script from project root dir:
[source,shell]
----
./tools/pulsar/docker/standalone/pulsar-destroy.sh
----

==== Mac M1 (Arm64)
If you are running on Mac M1 (ARM64) and have issues running the above commands,
instead use the scripts with the `-arm64` suffix. There is one for each command.

* `./tools/pulsar/docker/standalone/pulsar-start-arm64.sh`
* `./tools/pulsar/docker/standalone/pulsar-stop-arm64.sh`
* `./tools/pulsar/docker/standalone/pulsar-kill-arm64.sh`

Also note that the two docker volumes used in this case are also suffixed accordingly:

* `pulsardata-arm64`
* `pulsarconf-arm64`

'''
More information can be found in the official https://pulsar.apache.org/docs/next/getting-started-docker[Pulsar docs].
