[[native-images]]
= GraalVM Native Image Support

include::../attributes/attributes.adoc[]

https://www.graalvm.org/native-image/[GraalVM Native Images] are standalone executables that can be generated by processing compiled Java applications ahead-of-time. Native Images generally have a smaller memory footprint and start faster than their JVM counterparts.

.Support
The required https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#core.aot.hints[AOT Runtime Hints] are built-in to Spring for Apache Pulsar so that it can seamlessly be used in native image based Spring applications.

[NOTE]
====
The native image support in Spring for Apache Pulsar has been tested in basic scenarios, and we expect it to "just work". However, it is possible that more advanced use cases could surface the need to add additional runtime hints to your own application. If this occurs please file a {github}/issues[Github issue] with some details.
====

.Next Steps
If you are interested in adding native image support to your own application then an excellent place to start is the https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#native-image[Spring Boot GraalVM Support] section of the Spring Boot reference docs.

Although there is no reference to Spring for Apache Pulsar in the aforementioned guide, you can find specific examples at the following coordinates:

* https://github.com/spring-projects/spring-aot-smoke-tests/tree/main/integration/spring-pulsar[Spring for Apache Pulsar (imperative)]
* https://github.com/spring-projects/spring-aot-smoke-tests/tree/main/integration/spring-pulsar-reactive[Spring for Apache Pulsar (reactive)]
