[[micrometer]]
= Observability

:github: https://github.com/spring-projects/spring-pulsar
:micrometer-docs: https://docs.micrometer.io/

Spring for Apache Pulsar includes a way to manage observability through https://micrometer.io/[Micrometer].

NOTE: Observability has not been added to the Reactive components yet


[[observation]]
== Micrometer Observations
The `PulsarTemplate` and `PulsarListener` are instrumented with the Micrometer observations API.
When a Micrometer `ObservationRegistry` bean is provided, send and receive operations are traced and timed.

=== Custom tags
The default implementation adds the `bean.name` tag for template observations and `listener.id` tag for listener observations.
To add other tags to timers and traces, configure a custom `PulsarTemplateObservationConvention` or `PulsarListenerObservationConvention` to the template or listener container, respectively.

TIP: You can subclass either `DefaultPulsarTemplateObservationConvention` or `DefaultPulsarListenerObservationConvention` or provide completely new implementations.

include::partial$_metrics.adoc[]

include::partial$_spans.adoc[]

See {micrometer-docs}/tracing/reference[Micrometer Tracing] for more information.

=== Manual Configuration without Spring Boot
If you do not use Spring Boot, you need to configure and provide an `ObservationRegistry` as well as Micrometer Tracing. See {micrometer-docs}/tracing/reference[Micrometer Tracing] for more information.

=== Auto-Configuration with Spring Boot
If you use Spring Boot, the Spring Boot Actuator auto-configures an instance of `ObservationRegistry` for you.
If `micrometer-core` is on the classpath, every stopped observation leads to a timer.

Spring Boot also auto-configures Micrometer Tracing for you. This includes support for Brave OpenTelemetry, Zipkin, and Wavefront. When using the Micrometer Observation API, finishing observations leads to spans reported to Zipkin or Wavefront. You can control tracing by setting properties under `management.tracing`. You can use Zipkin with `management.zipkin.tracing`, while Wavefront uses `management.wavefront`.

==== Example Configuration
The following example shows the steps to configure your Spring Boot application to use Zipkin with Brave.

. Add the required dependencies to your application (in Maven or Gradle, respectively):
+
[tabs]
======
Maven::
+
[source,xml,indent=0,subs="verbatim,attributes",role="primary"]
----
<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-tracing-bridge-brave</artifactId>
    </dependency>
    <dependency>
        <groupId>io.zipkin.reporter2</groupId>
        <artifactId>zipkin-reporter-brave</artifactId>
    </dependency>
    <dependency>
        <groupId>io.zipkin.reporter2</groupId>
        <artifactId>zipkin-sender-urlconnection</artifactId>
    </dependency>
</dependencies>
----
======
+
[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Gradle
----
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
    implementation 'io.zipkin.reporter2:zipkin-sender-urlconnection'
}
----
+
NOTE
You need the `'io.zipkin.reporter2:zipkin-sender-urlconnection'` dependency only if your application does not have a configured WebClient or RestTemplate.
. Add the required properties to your application:
+
[source,yaml,indent=0,subs="verbatim"]
----
management:
  tracing.enabled: true
  zipkin:
    tracing.endpoint: "http://localhost:9411/api/v2/spans"
----
+
The `tracing.endpoint` above expects Zipkin is running locally as described https://zipkin.io/pages/quickstart.html[here].

At this point, your application should record traces when you send and receive Pulsar messages. You should be able to view them in the Zipkin UI (at http://localhost:9411, when running locally).

TIP: You can also see the preceding configuration on the link:{github}/blob/main/spring-pulsar-sample-apps/README.adoc[Spring for Apache Pulsar Sample Apps].

The steps are very similar to configuring any of the other supported Tracing environments.
