[[reactive-pulsar]]
= Reactive Support
:page-section-summary-toc: 1

The framework provides a Reactive counterpart for almost all supported features.

[TIP]
====
If you put the word `Reactive` in front of a provided imperative component, you will likely find its Reactive counterpart.

* `PulsarTemplate -> ReactivePulsarTemplate`
* `PulsarListener -> ReactivePulsarListener`
* `PulsarConsumerFactory -> ReactivePulsarConsumerFactory`
* etc..
====

However, the following is not yet supported:

* Error Handling in non-shared subscriptions
* Accessing Pulsar headers via `@Header` in streaming mode
* Observations

== Preface

NOTE: We recommend using a Spring-Boot-First approach for Spring for Apache Pulsar-based applications, as that simplifies things tremendously.
To do so, you can add the `spring-pulsar-reactive-spring-boot-starter` module as a dependency.

NOTE: The majority of this reference expects the reader to be using the starter and gives most directions for configuration with that in mind.
However, an effort is made to call out when instructions are specific to the Spring Boot starter usage.
