[[reactive-pulsar-client]]
= Reactive Pulsar Client
include::../../attributes/attributes.adoc[]

When you use the Reactive Pulsar Spring Boot Starter, you get the `ReactivePulsarClient` auto-configured.

By default, the application tries to connect to a local Pulsar instance at `pulsar://localhost:6650`.
This can be adjusted by setting the `spring.pulsar.client.service-url` property to a different value.

TIP: The value must be a valid {apache-pulsar-docs}/client-libraries-java/#connection-urls[Pulsar Protocol] URL

There are many other application properties (inherited from the adapted imperative client) available to configure.
See the {spring-boot-pulsar-config-props}[`spring.pulsar.client.*`] application properties.

[[reactive-client-authentication]]
== Authentication
To connect to a Pulsar cluster that requires authentication, follow xref:reference/pulsar/pulsar-client.adoc#client-authentication[the same steps] as the imperative client.
Again, this is because the reactive client adapts the imperative client which handles all security configuration.
