name: Trivy Vulnerability Scan (Repo mode) Dispatcher (1.2.x)

on:
  schedule:
    - cron: '0 16 * * */3' # Once every 3 day at 16:00 UTC
  workflow_dispatch:

jobs:
  dispatch_trivy_workflow:
    name: Dispatch scan workflow
    if: github.repository == 'spring-projects/spring-pulsar'
    strategy:
      matrix:
        # List of active maintenance branches.
        branch: [ 1.2.x ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Dispatch
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
        run: gh workflow run trivy-scan.yml -r ${{ matrix.branch }}
